name: Build
description: Build nginx image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build and push image to docker.io
    env:
      NGINX_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
      DOCKER_REGISTRY: docker.io
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
  - name: Build and push amd64 image to wodby registry
    env:
      NGINX_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: linux/amd64
      DOCKER_REGISTRY: registry.wodby.com
    run: |
      set -e
      DOCKER_USERNAME="${WODBY1_REGISTRY_USERNAME}" DOCKER_PASSWORD="${WODBY1_REGISTRY_PASSWORD}" . $GITHUB_ACTION_PATH/release.sh
    shell: bash
